Repository gradsflow/fastserve-ai, pull requests merged in 2024-03, with the labels that each got.

#26 Feature/server containerization
  README.md
  examples/docker-compose-example/Dockerfile
  examples/docker-compose-example/api.py
  examples/docker-compose-example/docker-compose.yml
  examples/docker-compose-example/requirements.txt
Labels: enhancement, example

#28 Feature/hf models
  README.md
  src/fastserve/models/__init__.py
  src/fastserve/models/__main__.py
  src/fastserve/models/huggingface.py
Labels: enhancement

#35 reorganize models
  README.md
  docs/404.md
  docs/fastserve/containerization.md
  docs/fastserve/models/face_detection.md
  docs/fastserve/models/image_classification.md
  docs/fastserve/models/image_gen.md
  docs/fastserve/models/llms/hf.md
  docs/fastserve/models/llms/local_llm.md
  docs/fastserve/models/llms/vllm.md
  src/fastserve/models/__init__.py
  src/fastserve/models/__main__.py
  src/fastserve/models/cv/__init__.py
  src/fastserve/models/cv/face_reco.py
  src/fastserve/models/cv/image_classification.py
  src/fastserve/models/image_gen/sdxl_turbo.py
  src/fastserve/models/llms/__init__.py
  src/fastserve/models/llms/huggingface.py
  src/fastserve/models/llms/llama_cpp.py
  src/fastserve/models/llms/vllm.py
Labels: documentation

#36 [Snyk] Upgrade vue from 3.4.19 to 3.4.20
  mkdocs.yml
  src/ui/package-lock.json
  src/ui/package.json
Labels: CI

#37 Add-badges
  README.md
  docs/index.md
Labels: documentation
